### ISSUE TITLE
改行

### ISSUE THREAD

**Issue by c0a21151** [Liunan0721/ProjExD#2]
https://github.com/Liunan0721/ProjExD/blob/f458e49a5ab0414d109064457d1f98d5f2595134/ex01/alphabet.py#L40

「正解です。」で改行した方が良いかも

**Comment by Liunan0721** [comment]
コミットありがとうございます。ほかのメンバーから同じコミットを受けてもう改行しました！

**Comment by Liunan0721** [comment]
コミットありがとうございます。ほかのメンバーから同じコミットを受けてもう改行しました！
