### ISSUE TITLE
引数

### ISSUE THREAD

**Issue by c0a21151** [Liunan0721/ProjExD#5]
https://github.com/Liunan0721/ProjExD/blob/1a9e523f30c7c49473d59b7ef864a93cdb2513a4/ex03/maze.py#L38

画像が違うから引数は変えた方が良いと思う

**Comment by Liunan0721** [comment]
コメントありがとうございました、こうかとんをほかの画像に変更したいので、同じ引数で大丈夫だと思います。ごめんなさい！
